# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Anime Dataset

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  job_1:
    name: Python Crawler
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9.x'
      
      
    - name: Install Dependence
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/deepghs/waifuc.git
        pip install gchar di-toolkit
    - name: Run spider
      run: python sp_gitact.py --hf_token ${{ secrets.HF_TOKEN }}
